#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/dokotlin
#    username: sa
#    password:
#
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show-sql: false
#        format_sql: true
#    open-in-view: false
#    database: h2
#
#logging:
#  level:
#    # org.hibernate.SQL: debug
#    com.yolo.dokotlin: debug
#    # org.hibernate.type: trace
#server:
#  port: 18081
